### ISSUE TITLE
Appveyor

### ISSUE THREAD

**Issue by sjotterman** [sjotterman/js-dev-env#14]
Re-enable appveyor CI. Stopped because I couldn't figure out how to work with headless chrome. This is what I had for appveyor.yml:

```
# Test against this version of Node.js
environment:
  matrix:
    # node.js
    - nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps:  Install-Product node $env:nodejs_version
  # Install modules
  - npm install

# Post installl test scripts
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # start server for UI tests
  - start /min npm run open:src
  # run tests
  - npm test

# Don't actually build
build: off

```
